version: '3'

services:
  backend:
    restart: always
    build: ./
    container_name: backend
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - db
  db:
    restart: always
    container_name: db
    image: "romeoz/docker-postgresql:11"
    ports:
      - "8001:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql
    environment:
      DB_NAME: "emailanalyzer"
      DB_USER: "dev"
      DB_PASS: "dev"
      PG_TRUST_LOCALNET: "true"
